language: node_js
before_deploy:
 - openssl enc -aes-256-cbc -d -salt -in ./cpanel_deploy.enc -out ./cpanel_deploy -pass pass:Aditya@9658
 - eval "$(ssh-agent -s)"
 - chmod 600 /tmp/cpanel_deploy
 - ssh-add /tmp/cpanel_deploy
script:
 - echo "Deploy!!"
after_success:
 - ssh jeetarts@tix.jeetvisualarts.com -o StrictHostKeyChecking=no
 - pwd