language: node_js
script:
 - echo "Deploy!!"
after_success:
 - set -e
 - sudo apt-get install -y lftp
 - lftp -c "set ftps:initial-prot ''; set ftp:ssl-force true; set ftp:ssl-protect-data true; set ssl:verify-certificate false; open ftp://jeetarts:Jeet@2512@eclipsetix.jeetvisualarts.com:21; mirror -eRv /home/jeetarts/eclipsetix.jeetvisualarts.com .; quit;" 